"""
Django settings for quiz_app_project.

Generated by 'django-admin startproject' using Django 4.2.25.
"""

import os
from pathlib import Path
import dj_database_url

# === Asosiy yo'l ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Xavfsizlik ===
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-default")

# Ishlab chiqishda True, serverda Railway muhitida False bo'lishi kerak
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    ".railway.app",
]

# === CSRF ===
CSRF_TRUSTED_ORIGINS = [
    "https://*.railway.app",
]

# === O'rnatilgan ilovalar ===
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Loyihangdagi app’lar
    "quiz.apps.QuizConfig",
    "homepage.apps.HomepageConfig",
]

# === Middleware ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# === URL va WSGI ===
ROOT_URLCONF = "quiz_app_project.urls"
WSGI_APPLICATION = "quiz_app_project.wsgi.application"

# === TEMPLATES ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# === Database ===
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}

# === Parol validatsiyasi ===
AUTH_PASSWORD_VALIDATORS = []

# === Til va vaqt zonasi ===
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Tashkent"
USE_I18N = True
USE_TZ = True

# === Statik fayllar ===
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# === Kirish va chiqish ===
LOGIN_URL = "/quiz/login/"
LOGIN_REDIRECT_URL = "/quiz/quiztype_list/"
LOGOUT_REDIRECT_URL = "/quiz/quiztype_list/"

# === Sessiyalar ===
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# === Default primary key ===
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
