"""
Django settings for quiz_app_project.

Generated by 'django-admin startproject' using Django 4.2.25.
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
load_dotenv()
# === Asosiy yo'l ===
BASE_DIR = Path(__file__).resolve().parent.parent

# === Xavfsizlik ===
SECRET_KEY = os.getenv('SECRET_KEY')

# Ishlab chiqishda True, serverda Railway muhitida False bo'lishi kerak
DEBUG = os.environ.get("DEBUG", "True") == "True"

ALLOWED_HOSTS = ['172.25.18.16', 'localhost', '127.0.0.1', '.onrender.com']

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# === CSRF ===
CSRF_TRUSTED_ORIGINS = [x.strip() for x in os.getenv('CSRF_TRUSTED_ORIGINS', 'http://localhost').split(',') if x.strip()]

# === O'rnatilgan ilovalar ===
INSTALLED_APPS = [
    'jazzmin',
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Loyihangdagi app’lar
    "quiz.apps.QuizConfig",
    "homepage.apps.HomepageConfig",
    'whitenoise.runserver_nostatic',

]

# === Middleware ===
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    'whitenoise.middleware.WhiteNoiseMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# === URL va WSGI ===
ROOT_URLCONF = "quiz_app_project.urls"
WSGI_APPLICATION = "quiz_app_project.wsgi.application"

# === TEMPLATES ===
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

JAZZMIN_SETTINGS = {
    "site_title": "Namangan Bojxonasi Custom Admin",
    "site_header": "BNRTEB",
    "welcome_sign": "Test yechish tizimiga xush kelibsiz",
    "copyright": "O.Xakimov © 2025",
    "show_sidebar": True,
    # ... more settings can be found in the official documentation
}



# === Database ===
DATABASE_URL = os.getenv('DATABASE_URL', '').strip()
if DATABASE_URL:
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL, conn_max_age=600)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
        }
    }

# === Parol validatsiyasi ===
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# === Til va vaqt zonasi ===
LANGUAGE_CODE = "en-us"
TIME_ZONE = "Asia/Tashkent"
USE_I18N = True
USE_TZ = True

# === Statik fayllar ===
STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# === Kirish va chiqish ===
LOGIN_URL = "/quiz/login/"
LOGIN_REDIRECT_URL = "/quiz/quiztype_list/"
LOGOUT_REDIRECT_URL = "/quiz/quiztype_list/"

# === Sessiyalar ===
SESSION_ENGINE = "django.contrib.sessions.backends.db"

# === Default primary key ===
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
