# Generated by Django 4.2.25 on 2025-11-01 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_multiple_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='is_multiple_choice',
            field=models.BooleanField(default=False),
        ),
    ]
